### ISSUE TITLE
How is this going?There are numerous loading on the webpage

### ISSUE THREAD

**Issue by hjq1001** [Midnight-Lizard/Midnight-Lizard#126]
How is this going?There are numerous loading on the webpage

**Comment by hjq1001** [comment]
![image](https://user-images.githubusercontent.com/35657236/41248903-fa46d516-6de4-11e8-85bb-39346e683777.png)

**Comment by pavel-agarkov** [comment]
It is a known issue.
I cannot reproduce it on the website you've mentioned, but a common solution should help:
Remove all limits from background (fond) images:
![image](https://user-images.githubusercontent.com/24639631/41249562-1f184956-6dbd-11e8-9f35-a8b709c65b27.png)

**Comment by hjq1001** [comment]
Thank you, your method is very effective!

**Comment by pavel-agarkov** [comment]
Closing it by now, but will try to fix properly in the future.
