### ISSUE TITLE
Do not show a black overlay when your addon is disabled in Firefox Nightly?

### ISSUE THREAD

**Issue by SpineEyE** [Midnight-Lizard/Midnight-Lizard#129]
When I "disable the entire extension" as the tooltip says on the big on/off button, it's actually not disabled and slows page load speed significantly, sometimes heavily. Additionally there is a black, half opaque overlay when I load a website. Sometimes it stays there for seconds when Midnight Lizard decides to slow down page load for that long.

**Comment by pavel-agarkov** [comment]
When you visit any website Midnight Lizard stores the latest brightness level and use it when you come back to this website next time to draw a dimmed cover to protect you from white splashes during initial page load. This cover can be seen only on less performant devices or with bad network connectivity.
So when extension is turned off the cover is shown only once when you first time load a page that was previously visited when extension was turned on. It won't be shown for the subsequent page loadings.
Even when the cover is shown it cannot decrease performance more then by 1% and when it is not shown extension has absolutely negligible impact on performance.
It should be something else that slows down your browser. Try to disable other extensions one by one to see a difference. To be sure disable them on `chrome://extensions` page. Also check whether you use the latest Chrome: chrome://settings/help
Midnight Lizard has a simplified mode that can significantly improve performance. Might worth to try it out as well. You can switch the mode on the Common tab and then press "Set as default" to use it on all websites by default.

**Comment by SpineEyE** [comment]
I want to apologize for my bad manners in the bug report but I still think that this is a bug. Also I should have mentioned that I'm using it on Firefox Nightly.

Why would you show a cover  "when you first time load a page that was previously visited when extension was turned on" ? When the extension is turned off I want it to behave as close as possible to as if I disable it completely in the browser. And as of now this is what I have to do to get my browser to an acceptable speed. Every morning I disable it in about:addons and every evening I have to re-enable it there. It has really gotten a burden and I already use a different addon that doesn't have this problem, but also unfortunately has less features.

To clarify: The seconds of wait time are produced when your addon is enabled and aren't, when your addon is disabled.

**Comment by pavel-agarkov** [comment]
I'm showing a cover when website opened for the first time after extension was turned off because there is no synchronous way to check whether extension is active or not. So I have to rely on the data stored locally on this website since last visit when extension was probably active. Then I can retrieve actual extension state and continue processing or just quit. Without this first preload phase you would see white screen first for a while.
But there was actually a bug that cause showing a cover all the time (not for the first time only).
I have just fixed it and will publish an update soon.
This might also fix this issue so I am reopening it until you confirm that it is fixed.

**Comment by pavel-agarkov** [comment]
The new version has been published.
Please check it out and give a feedback here.
Thank you.

**Comment by SpineEyE** [comment]
Performance is significantly better now, thank you.

From what you wrote it can probably not be fixed
