### ISSUE TITLE
Popup closes on loss of focus

### ISSUE THREAD

**Issue by Koolstr** [Midnight-Lizard/Midnight-Lizard#139]
I'm trying out ML in Firefox now, and it seems buggier than Chrome's. The lack of scrollbar themeing is unfortunate too. :(
When copying settings from my Chrome version, I had to constantly switch between the displays. While Chrome's ML popup stayed open even when I switched to Firefox, the inverse was not the case. Firefox's popup would close whenever I would switch to Chrome.
I had to do these manual settings copying since you can't seem to import color schemes to the Firefox version either, likely due to the same issue. When I click on 'Import,' it first closes the popup before it opens a file select dialog. So when I select a file, nothing happens, it seems. The color scheme does not get imported. I imagine this is a connected problem.

**Comment by pavel-agarkov** [comment]
Hi Jeffrey!
Firefox version is completely the same as Chrome's one - the source code is the same and it is here.
Firefox does not have any way to style scrollbars from within Web Extensions - there is nothing I can do with it.

Yes, Firefox closes popups and I hate this "feature". There is a way to keep it opened but only in debug mode which is not available to users. And yes, the same problem makes impossible to import settings - when open file dialog becomes active Firefox closes popup so there is no place to return dialog results...

> When the user clicks the button, the popup is shown. When the user clicks anywhere outside the popup, the popup is closed. The popup can be closed programmatically by calling `window.close()` from a script running in the popup. However, you can't open the popup programmatically from an extension's JavaScript; it can be opened only in response to a user action.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Popups

The only way is to open Chrome and Firefox side by side (split the screen) and save settings after each settings tab, then select next tab in Chrome and reopen popup in Firefox and continue editing the same color scheme.

In the future it will be possible to share settings between different browsers via Midnight Lizard website and I'm currently working on it.

**Comment by Koolstr** [comment]
I presumed that was the case for both. That is how I had to go about making the settings import.
It sucks that there isn't a way to have it work natively, but if you are building a workaround, then that is awesome and I look forward to it. :D 
I would at least put a notice in the FF version by the import button, saying that imports won't work. Either that, or disable the button entirely.
Is there any way for us to be suggesting these two changes to Firefox's devs? They may not support them now, but they could in the future, if we initiate the ideas at this time.

**Comment by pavel-agarkov** [comment]
That's a good point.
I will put notice on AMO and in popup itself (#141)
As about registering an issue for Firefox - I will try to find existing one or create a new one and let you know here.

**Comment by Koolstr** [comment]
AMO?
Thanks for being so proactive towards solving some of the minor problems of your users. You're a great dev :D

**Comment by pavel-agarkov** [comment]
AMO stands for Addons.Mozilla.Org
They call it this way.
