### ISSUE TITLE
Put notice about impossibility to import settings in Firefox

### ISSUE THREAD

**Issue by pavel-agarkov** [Midnight-Lizard/Midnight-Lizard#141]

**Comment by nomis** [comment]
It would be helpful to allow import on Firefox by pasting JSON in a text area.

I have no idea how I configured a Midnight-Lizard colour scheme to do what I want and the only way to replicate it is to copy every setting manually.

**Comment by pavel-agarkov** [comment]
If you don't want or can't use built-in sync functionality then you can bypass it with a little trick:
[HOW TO transfer all settings from one browser to another without using built in synchronization](https://github.com/Midnight-Lizard/Midnight-Lizard/wiki/HOW-TO-transfer-all-settings-from-one-browser-to-another-without-using-built-in-synchronization)

**Comment by nomis** [comment]
Ok, l'll try that. (I will never configure any add-on to login and sync things.)
