### ISSUE TITLE
Translation pop up icon

### ISSUE THREAD

**Issue by Zalext** [Midnight-Lizard/Midnight-Lizard#148]
Hi,
That's a great extensions!

The only problem I'm facing it's:
Using double click translation extensions, doesn't shows the translation icon.

![2018-07-23_225846](https://user-images.githubusercontent.com/28935637/43102652-fb903cca-8ecb-11e8-9e10-298bba613d5d.png)

![2018-07-23_225731s](https://user-images.githubusercontent.com/28935637/43102653-fbbd5c00-8ecb-11e8-8bb5-88396319e091.png)

Is happening on Opera [ImTranslator](http://www.imtranslator.net/Translator-For-Opera-Google-Translate.asp) and Chrome [ImTranslator](http://imtranslator.net/Translator-for-Chrome-Imtranslator.asp)

Would this be fixed?

Thank you.

**Comment by pavel-agarkov** [comment]
The whole logic of this extension seams to be tied up with background color for some reason.
Here's their method of showing translation icon:
![image](https://user-images.githubusercontent.com/24639631/43127254-ba0c3e0e-8f37-11e8-96e2-aa8bda1c4a54.png)
So basically they show it only if there is no background color...
And it is not the only place - a lot of other things tied the same way.
But the whole point of Midnight Lizard is to change background color.
Looks like there is nothing we can do - these two extensions cannot work together.

**Comment by pavel-agarkov** [comment]
You can try official [Google translate extension](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb). Midnight Lizard has custom logic to make sure this extension works correctly.

**Comment by Zalext** [comment]
Thanks for check it.

I've tested the extension but it's less powerful than IMT.
I'll ask them to fix it pointing to your explanation.

Thank you very much!
