### ISSUE TITLE
Treat emphasized text as highlighted.

### ISSUE THREAD

**Issue by pavel-agarkov** [Midnight-Lizard/Midnight-Lizard#152]
Use HighlightedText component for `<em>` elements

**Comment by pavel-agarkov** [comment]
Нет, удалять не нужно - есть специально для таких случаев кнопки:
- Удалить настройки текущего сайта
- Удалить все настройки = вернуть все умолчания

![image](https://user-images.githubusercontent.com/24639631/43686477-740a88c4-98cf-11e8-85ed-f713a9732328.png)

**Comment by Mirokodin** [comment]
A настройки цветовой схемы По Умолчанию, тоже вернутся к своим первоначальным настройкам? А то я там накрутил всякого... или я не понимаю как работает аддон. 

A этот сайт не возможно затемнить?: https://chrome.google.com/webstore/category/extensions?hl=ru

**Comment by pavel-agarkov** [comment]
> A настройки цветовой схемы По Умолчанию, тоже вернутся к своим первоначальным настройкам? А то я там накрутил всякого... или я не понимаю как работает аддон.

Да, эта кнопка просто удаляет вообще все данные... Поэтому всё вернется как было при установке.

> A этот сайт не возможно затемнить?: https://chrome.google.com/webstore/category/extensions?hl=ru

На этом сайте браузер запрещает запускать расширения.
(как и на всех системных страницах и меню браузера и всех страницах и меню других расширений)
Т.е. все эти страницы невозможно затемнить никаким расширением.

**Comment by Mirokodin** [comment]
Извини если я пишу не в той теме...
Подскажи пожалуйста как осветлить значки на картинке, которые очень темные?
Вот сайт: https://www.mercadolibre.com.ar/
![2018-08-05_114600](https://user-images.githubusercontent.com/42102024/43687079-d56fab14-98a5-11e8-8217-45eb4b19626c.jpg)

**Comment by pavel-agarkov** [comment]
Никак не получится без подключения дополнительных расширений (но ради одного сайта точно не стоит).
Эти значки (и надпись как ни странно тоже) представляют из себя элемент `<img>`, который я не инвертирую - инвертируются только маленькие фоновые изображения, так как это является стандартом для отображения иконок.

**Comment by Mirokodin** [comment]
Все, буду рекомендовать твою программу своим друзьям! Огромное спасибо, я почти во всем разобрался. Осталось понять как синхронизировать настройки с онлайн аккаунтом типа гугл или еще каким или для переноса с компа на комп.

У тебя есть желание получать идеи и по другим программам, аддонам, которые ты бы смог внедрить?
Например я уже давно ищу аддон для хрома, который объединяет в себе и управление жестом мышки и select like a boss (выделение части текста ссылки левой кнопкой). 

Можно еще реализовать вкладки для расширений или объединение их в одну кнопку например, а то значки занимают половину адресной строки, а убирать значки не хочу, так как часто ими пользуюсь.

Короче если подумать и задастся целью, могу напридумывать много идей. Не ручаюсь за то, что все они будут хорошими, надо будет многое отсеивать, сортировать, изменять или переделывать, но можно найти и отличные идеи, был бы тот, кто сможет их реализовать... :)
Люблю искать идеи, без которых будет невозможно обойтись... ;)

**Comment by pavel-agarkov** [comment]
> Осталось понять как синхронизировать настройки с онлайн аккаунтом типа гугл или еще каким или для переноса с компа на комп.

Все настройки Midnight Lizard синхронизируются по умолчанию, если выполнен вход в браузер.

> У тебя есть желание получать идеи и по другим программам, аддонам, которые ты бы смог внедрить?

Мне будут интересны замечания/предложения по данному расширению, а других у меня нет и в ближайшее время не планируется появление в виду хронической нехватки времени.

> Можно еще реализовать вкладки для расширений или объединение их в одну кнопку например, а то значки занимают половину адресной строки, а убирать значки не хочу, так как часто ими пользуюсь.

Значки расширений можно прятать в меню хрома, а вот каким либо образом изменить их положение/вид с помощью другого расширения думаю невозможно.

**Comment by pavel-agarkov** [comment]
will look like this:
![image](https://user-images.githubusercontent.com/24639631/45952134-b5fafc80-c00e-11e8-8a38-ebad9aaa4ba5.png)
