### ISSUE TITLE
[Bug?] When it's enabled on wikipedia, sort buttons at form's column header won't scale well

### ISSUE THREAD

**Issue by Retia-Adolf** [Midnight-Lizard/Midnight-Lizard#154]
https://en.wikipedia.org/wiki/Comparison_of_text_editors

![image](https://user-images.githubusercontent.com/34053927/43889608-aae67036-9b92-11e8-9c89-614814a526f3.png)

**Comment by pavel-agarkov** [comment]
the fix will be available in the next release.
