### ISSUE TITLE
#extensions-on-chrome-urls

### ISSUE THREAD

**Issue by Gubith** [Midnight-Lizard/Midnight-Lizard#155]
Any chance making use of this chrome://flags/#enable-panels
> Extensions on chrome:// URLs
> Enables running extensions on chrome:// URLs, where extensions explicitly request this permission. – Mac, Windows, Linux, Chrome OS, Android
> #extensions-on-chrome-urls

BTW Google should bring you on as Lead UI Dev for all projects.

**Comment by pavel-agarkov** [comment]
I've tried this already, but unfortunately Chrome UI is based on polymer and heavily depends on Shadow DOM, so Midnight Lizard cannot completely override their styles. It would look something like this:
![image](https://user-images.githubusercontent.com/24639631/44018830-ad8a6774-9ee5-11e8-82fa-3df7a94a394a.png)
