### ISSUE TITLE
This one repo LICENSE status is?

### ISSUE THREAD

**Issue by freedom5566** [Midnight-Lizard/Midnight-Lizard#213]
Hi，I find repo license is MIT.
package.json license show GPL-3 ?
MIT or GPL3?
https://github.com/Midnight-Lizard/Midnight-Lizard/blob/53e30f5deedafbcf94969d0053faa8e89cba5ed3/package.json#L7
Thank you contribution,I very like Midnight-Lizard! :)

**Comment by pavel-agarkov** [comment]
It's MIT.
I forgot to change it in package file.
Thank you.
