### ISSUE TITLE
Greyscale schemes should exclude colour

### ISSUE THREAD

**Issue by grahamperrin** [Midnight-Lizard/Midnight-Lizard#214]
From <https://www.reddit.com/comments/aabdaz/-/eg2slw1/?context=1>: 

> …  with Reddit.
> 
> _Inverted Greyscale_ includes inverted colours, which can't be right.

**Comment by pavel-agarkov** [comment]
Thank you for the feedback.
Can you please provide a screenshot where you can highlight what the problem exactly is?
Midnight Lizard only inverts small background images to preserve their contrast ration against the background. 
Only 10% of the original background images saturation is left in the predefined version of Inverted Grayscale color scheme:
![image](https://user-images.githubusercontent.com/24639631/52519626-4d37b800-2c6f-11e9-8079-b454de7e0b8b.png)
And you can decrease it even more to completely remove all colors.

**Comment by grahamperrin** [comment]
OK, my bad, I imagined that 'greyscale' should be greys alone (no colours). The expanse of blue was striking: 

![image](https://user-images.githubusercontent.com/192271/52522764-8b3dd780-2c81-11e9-9c72-f5cb8ccfd025.png)

**Comment by pavel-agarkov** [comment]
Actually the top blue bar is not supposed to be that blue (unless you've changed some settings)
Here's how it looks for me with 10% saturation:
![image](https://user-images.githubusercontent.com/24639631/52523179-99025580-2c9f-11e9-9c0e-117d5506c4e7.png)

**Comment by grahamperrin** [comment]
I hadn't changed settings, I got the blueness repeatedly. 

I imagined an extensions conflict with [Blacken](https://addons.mozilla.org/addon/blacken/) but now I can't reproduce anything like the blueness: 

![image](https://user-images.githubusercontent.com/192271/52551095-fba83e00-2dd2-11e9-94ab-876524dbf0e5.png)
