### ISSUE TITLE
Overwrites syntax highlighting for code examples

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [Midnight-Lizard/Midnight-Lizard#217]
Reproduce: apply Midnight Lizard theme, go to some page with code on it (not github, seems to be fine.)

https://angular.io/tutorial/toh-pt6

Highlighting has gone

**Comment by pavel-agarkov** [comment]
Syntax highlighting is preserved only in Complex mode.
When page is big (like in your example) processing mode can be switched to Simplified.
You can increase number of elements necessary for automatic mode switch or use Complex mode.
![image](https://user-images.githubusercontent.com/24639631/52962754-28e68480-33af-11e9-8f02-fbe4e10a86e2.png)


PS: also increase text saturation limit to preserve its original level
PPS: in the next version I'm going to add one more mode and it will also preserve syntax highlighting

**Comment by mark-jordanovic-lewis** [comment]
Beautiful Thanks very much for teh rapid response. I had ML in  complex mode but restarting the browser did the job. Thanks so much for this eyesaving beauty!
