### ISSUE TITLE
Color scheme generator

### ISSUE THREAD

**Issue by pavel-agarkov** [Midnight-Lizard/Midnight-Lizard#224]
Add UI to generate color scheme from a set of web colors (hex,rgb,hsl,etc...)

**Comment by ghost** [comment]
Wait. Why is this closed? How can I set rgb hex to background color scheme? I can't find it.
I want to set background to be #202000 How can I do it. I only see hue slider (which is inaccurate).

**Comment by pavel-agarkov** [comment]
@pc00per 
Got to Color schemes tab and press Color schemes generator.
Make sure your current color scheme is similar to what you want to achieve at the end.

**Comment by ghost** [comment]
> @pc00per Got to Color schemes tab and press Color schemes generator. Make sure your current color scheme is similar to what you want to achieve at the end.

Okay tq. Btw lil offtopic. Some websites still retain their own scheme (such as GitHub). How to override them with mine?

**Comment by pavel-agarkov** [comment]
if you mean that github uses its own dark scheme then you need to turn it off in github settings
ps: I use github theme and disabled ML there with Alt+Shift+L

**Comment by ghost** [comment]
> if you mean that github uses its own dark scheme then you need to turn it off in github settings ps: I use github theme and disabled ML there with Alt+Shift+L

Ya that works. But we can't be sure for all websites. Some strictly have their own schemes right.

**Comment by pavel-agarkov** [comment]
sure, midnight lizard just adapts existing color scheme on the website to the selected one in the ML - but does not override it.
unless you use simplified processing mode but it is not suitable for most websites.
