### ISSUE TITLE
Only style scrollbars

### ISSUE THREAD

**Issue by Splike** [Midnight-Lizard/Midnight-Lizard#231]
I'd like the option, to make a color scheme, where *only* scrollbars are styled and nothing else. But sadly it doesn't seem possible.

**Comment by pavel-agarkov** [comment]
Visually it is possible, but it will still process much more then just scrollbars and it would make more sense to use other extensions that provide specifically scrollbars styling.
Also it is possible to copy and slightly modify scrollbars styling from Midnight Lizard and use it in other extensions like Stylus:
https://github.com/Midnight-Lizard/Midnight-Lizard/blob/4b4324efb448f442819d036d6290f8e4e0c6d4ab/css/dynamic-universal.css#L46-L148

**Comment by Splike** [comment]
I see. I had hoped to do it with midnight lizard, as it is very easy to enable and disable for specific sites. But I understand your point with the over-processing. Thanks for your quick reply!

**Comment by pavel-agarkov** [comment]
But you can give it a try by yourself with bright color schemes like Increased Contrast as starting point and modify scrollbars there:
![image](https://user-images.githubusercontent.com/24639631/56613991-8e115d00-6620-11e9-9a0d-4d7fac2a7be5.png)

**Comment by Splike** [comment]
I actually tried that, but I couldn't really get **only** scrollbars to be changed. So I've gone ahead with your other suggestion, to make a style. I'm so close to getting it done, but I'm currently stuck on a regex problem.

If you know regex, maybe you can help? I made a reddit post explaining the problem [here](https://www.reddit.com/r/regex/comments/bgmtf1/help_website_matching_using_negativelookahead/). If not, that's fine. I really appreciate your help! Thanks!

**Comment by pavel-agarkov** [comment]
Instead of fancy regex it might be easier to specify the list of websites as is and it would work even faster.

**Comment by Splike** [comment]
I went with your suggestion before reading it. After a whole lot of time spent on that regex (which I actually got working in the end.) I realised that Midnight Lizard will just override it anyway.

So I will just be continually updating my list of domains for sites that I disable midnight lizard.

Oh well. At least it was a good learning experience 😃
