### ISSUE TITLE
Export color scheme broken

### ISSUE THREAD

**Issue by Splike** [Midnight-Lizard/Midnight-Lizard#232]
The feature is broken. Clicking the export button does nothing. I expected it to open a window, letting me choose the location where to save the .json file

**Comment by pavel-agarkov** [comment]
What is your browser and what exactly is happening for you?
In most browsers there will be a file in the standard downloads section.
In Chrome it will look like this:
![image](https://user-images.githubusercontent.com/24639631/56613602-a46ae900-661f-11e9-804a-47603120918f.png)
So it is up to the browser how to do export - I cannot control it.

**Comment by Splike** [comment]
I'm using the Chromium based browser Vivaldi

Vivaldi | 2.4.1488.38 (Stable channel) (64-bit)
-- | --
Revision | 2640e650a34b63b6befd0c419f417523b8f0ce2b
OS | Windows 10 OS Build 16299.1029
JavaScript | V8 7.3.492.27
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.105 Safari/537.36 Vivaldi/2.4.1488.38

**Comment by pavel-agarkov** [comment]
Vivaldi applies a lot of limitations on popup windows and blocks some of Midnight Lizard's functionality.
Previously it used to be possible to export color schemes there but you would have hard time importing them back into Vivaldi anyway...

**Comment by Splike** [comment]
Ah, what a shame. The weird thing is, when I click import, I actually get a window, letting me locate a json file. I would expect both buttons to be broken, if there actually is a limitation on popup windows.

**Comment by pavel-agarkov** [comment]
Yes - you have a window, but when you choose a file it won't be imported since Vivaldi blocks message boxes as well.
This is a well known problem and I even reported it to them, but they just ignore everything and they don't even have a public issue tracker...

**Comment by Splike** [comment]
Damn, that super frustrating! Oh well, I'll just have to live with it I guess.

**Comment by pavel-agarkov** [comment]
Closing it for now. Feel free to comment if necessary.
