### ISSUE TITLE
Whitelist instead of blacklist

### ISSUE THREAD

**Issue by FranklinYu** [Midnight-Lizard/Midnight-Lizard#238]
I want the default to be “disabled” but I can enable it for some sites. Is it possible with current extension?

**Comment by pavel-agarkov** [comment]
Hi Franklin!
Yes, it is possible. Just open 'Global settings' tab and uncheck 'Run on all websites by default'.
That's it - no need to press 'Apply' or 'Save'.
Later when you wnat to use Midnight Lizard on some website you can simply press Alt+Shift+L shortkey to eneble just for the current website.
