### ISSUE TITLE
XML files display as text in Firefox if Midnight Lizard is loaded

### ISSUE THREAD

**Issue by ScoreUnder** [Midnight-Lizard/Midnight-Lizard#239]
If Midnight Lizard is enabled (not necessarily switched on) in Firefox, then XML files will show as plain text with tags stripped.

Normally in Firefox, XML files without an accompanying XSLT should display as an interactive tree structure.

**Comment by pavel-agarkov** [comment]
Can you provide a screenshot?
For me it looks like this:
![image](https://user-images.githubusercontent.com/24639631/62246496-67677d00-b3ec-11e9-8d1f-8cc06b00d0e2.png) [url](https://www.w3schools.com/xml/note.xml)
And it does not mater enabled Midnight Lizard or not and which processing mode is used.
But in my case Midnight Lizard adds attributes to the root element.

**Comment by ScoreUnder** [comment]
For me it looks like this when enabled: https://i.imgur.com/x5qGqTQ.png
And like this when disabled: https://i.imgur.com/8nxvohj.png

This is Firefox Developer Edition 69.0b10 (64-bit) on Arch Linux

**Comment by xcasxcursex** [comment]
Running latest nightly on Windows (77.0a1 (2020-04-26)) mine is like so: 

![image](https://user-images.githubusercontent.com/58130821/80317088-1b474d00-8845-11ea-8f67-181b7b352390.png)

Not darkened, but not text either.

**Comment by pavel-agarkov** [comment]
I believe there is no way to style xml documents without custom xml viewer creation which is not the goal of this extension.

**Comment by McNippleson** [comment]
This is closed but I have the exact same issue, FF 84.0.2

**Comment by xcasxcursex** [comment]
Latest FF, still working fine, unstyled, but not the plaintext one-liner shown above.

If this is a problem with ML, it's in conjunction with something else, which I obviously don't have.
