### ISSUE TITLE
Add the option to do not change the links original color

### ISSUE THREAD

**Issue by serovar** [Midnight-Lizard/Midnight-Lizard#241]

**Comment by pavel-agarkov** [comment]
There is already this option although it is very far from being intuitive: you need to set both default saturation and default hue gravity to zero on the Links tab like this:
![image](https://user-images.githubusercontent.com/24639631/63802520-81c54580-c91b-11e9-9c86-9d36f66e76aa.png)
This way each link on the page will have the original hue.
If you also want to keep the original links brightness then you can decrease contrast level as well.
But the later will make links too dark on most websites.
