### ISSUE TITLE
Feature Request: Every page blacklisted by default

### ISSUE THREAD

**Issue by msegmx** [Midnight-Lizard/Midnight-Lizard#242]
Thanks for providing a great extension. But I have a request:

Is it possible to switch the default behavior of ML so that it inverts pages only on user interaction?
In other words; currently, when ML is active, it inverts every page by default. My request is the opposite behavior: 

- ML is active but won't invert the page / stays passive by default
- if the user want a site to be inverted, he/she clicks on the ML icon
- ML inverts the page and remembers the decision

**Comment by pavel-agarkov** [comment]
It is already possible:
1) Got to Global settings tab in Midnight Lizard's popup
2) Uncheck "Run on all websites by default"
3) When you are on a website where you want to use Midnight Lizard - just press Alt+Shift+L to activate it only on this website and your choice will be remembered.

**Comment by msegmx** [comment]
I somehow overlooked the Global Settings. 

Thanks !
