### ISSUE TITLE
White border left, right, top and bottom

### ISSUE THREAD

**Issue by brakenow** [Midnight-Lizard/Midnight-Lizard#244]
Running Firefox 70. Would like to remove it.

**Comment by pavel-agarkov** [comment]
I'm not sure what exactly you mean.
If you are talking about html elements' border on the page then you can change it color as you wish.
There are Borders tab in the settings specifically for that.
If you want it to be darker just decrease Brightness limit. Decreasing Contrast can also do the trick.  
Midnight Lizard does not add or remove elements to/from the page. So all the borders you see were there originally. But setting border color to be similar with background color can look like its removal.
