### ISSUE TITLE
Extension doesn't work properly in this site

### ISSUE THREAD

**Issue by InventM4n** [Midnight-Lizard/Midnight-Lizard#249]
https://elchapuzasinformatico.com/

Slow down my browser and I must deactivate it

**Comment by pavel-agarkov** [comment]
Yes, looks like this website it too heavy to be processed.
You can disable Midnight Lizard just on this website by pressing Alt+Shift+L
You can also try to change processing mode. **Simplified** mode works much better there:
![image](https://user-images.githubusercontent.com/24639631/73689163-aef1fd00-46de-11ea-8638-c0595e076be6.png)
