### ISSUE TITLE
Dark mode does not work in vivaldi for local files

### ISSUE THREAD

**Issue by somospocos** [Midnight-Lizard/Midnight-Lizard#250]
I am using Midnight Lizard with Nord theme and by default it does not work in vivaldi for local html files opened via Ctrl-O. Seems to be a vivaldi-only problem (Firefox works fine for both websites and local html files) and only for local files (opening a website in vivaldi, even a local one via http://locahost works fine).

I have tried to explicitly enforce the Nord theme via Midnight Lizard -> Activation, but when I set the include match pattern to **file:///*.*** I get a **None of the patterns match current page** under the textbox and the Nord theme still does not get applied to the opened local html file.

**Comment by pavel-agarkov** [comment]
It is forbidden by default in Chromium based browsers like Vivaldi.
To enable it please navigate to [vivaldi://extensions](vivaldi://extensions)
Find Midnight Lizard and open its Details
There just toggle: Allow access to file URLs
![image](https://user-images.githubusercontent.com/24639631/73969249-1f418e00-492c-11ea-9e48-b8b00e770004.png)

**Comment by somospocos** [comment]
Thank you. Perhaps including an explicit hint about in Activation dialog could be useful. I wasn't able to figure this on my own, only looked in Midnight Lizard's own settings many times before opening the issue.
