### ISSUE TITLE
Inversion doesn't work for Google Drive PDFs

### ISSUE THREAD

**Issue by devanshuDesai** [Midnight-Lizard/Midnight-Lizard#255]
<img width="1042" alt="Screen Shot 2020-04-03 at 7 35 55 PM" src="https://user-images.githubusercontent.com/37163544/78416979-5b1e6a00-75e2-11ea-8823-c7911ddc9b53.png">

**Comment by pavel-agarkov** [comment]
PDF files are displayed as images on Google Drive. Images are not inverted by Midnight Lizard.
