### ISSUE TITLE
Midnight Lizard bleed thru fix? 

### ISSUE THREAD

**Issue by bjm234** [Midnight-Lizard/Midnight-Lizard#256]
Hi
How may I fix Midnight Lizard bleed thru even with Midnight Lizard removed. 
Where are Global settings stored in Chrome and new Edge even with Midnight Lizard off and or removed?
I'd prefer to avoid having to clean install Chrome and new Edge.
<img width="839" alt="png_5751" src="https://user-images.githubusercontent.com/25015553/79344536-f88c6e80-7efd-11ea-9120-810535b93f4d.png">
<img width="960" alt="png_5753" src="https://user-images.githubusercontent.com/25015553/79344561-fde9b900-7efd-11ea-81a2-74ef50087659.png">
<img width="960" alt="png_5778" src="https://user-images.githubusercontent.com/25015553/79344596-093ce480-7efe-11ea-97c1-d5d671a64e8e.png">
I'd prefer to avoid having to clean install Chrome and new Edge.

**Comment by pavel-agarkov** [comment]
There is no way Midnight Lizard could cause this neither when turned on nor off.
Please check whether you have some other extensions installed.

**Comment by bjm234** [comment]
Okay - 
Where are Global settings stored in Chrome and new Edge?

**Comment by pavel-agarkov** [comment]
Global settings are stored the same way as all other Midnight Lizards settings by using [chrome.storage](https://developer.chrome.com/apps/storage) api as described in the extension [Privacy Policy](https://midnight-lizard.org/extension-privacy)

**Comment by bjm234** [comment]
Okay....I cannot locate path in my Chrome profile or my new Edge profile.  
Must be me. 
Thanks anyway.
