### ISSUE TITLE
report bug on djangoproject

### ISSUE THREAD

**Issue by amirhoseinpy** [Midnight-Lizard/Midnight-Lizard#257]
Hi.It has some bug at left side of : 
[djangoproject](https://djangoproject.com/)

**Comment by pavel-agarkov** [comment]
This website uses box-shadow to fill background with color.
This technique is highly uncommon and Midnight Lizard does not support box-shadow processing.
You can switch to Filter mode on that website to fix this issue:
![image](https://user-images.githubusercontent.com/24639631/79681701-c6904a80-8224-11ea-8b1f-80c1acf97516.png)
