### ISSUE TITLE
Exclude Elements

### ISSUE THREAD

**Issue by DeadlySurgeon** [Midnight-Lizard/Midnight-Lizard#258]
It would be nice to be able specify rules on excluding elements, for instance on gitlab it would be nice if I could tell it to exclude the class `code` so that I get the benefit of making things dark, without sacrificing my theme for code.

**Comment by pavel-agarkov** [comment]
Please take a look at this https://github.com/Midnight-Lizard/Midnight-Lizard/issues/234#issuecomment-494123486

**Comment by DeadlySurgeon** [comment]
@pavel-agarkov so is that just a work around?

**Comment by pavel-agarkov** [comment]
No, it is the way to go. It is used internally and can be used with external tools as well.
There are already too many options in Midnight Lizard to confuse most of the users.

**Comment by DeadlySurgeon** [comment]
Are you sure? Because from the looks of it, it seems like the solution would be to just install another Extension?

**Comment by pavel-agarkov** [comment]
Yes, why re-implement existing solutions when they do work well.
Most of the existing options in Midnight Lizard are used by a very few while others complain it is too difficult to use. So I prefer to add features without any settings.

**Comment by DeadlySurgeon** [comment]
A bit late because of issues, but the reason why to "re-implement" it is that I some people, like myself, only have a limited range of extensions that can be installed on work computers. Plus extensions shouldn't be reliant on each other.
