### ISSUE TITLE
Scheduling theme change in 30 or 15-minute increments

### ISSUE THREAD

**Issue by maciejmotyka** [Midnight-Lizard/Midnight-Lizard#262]
Regardless of whether #178 gets implemented or not, I find the current increment of 1 hour in manual scheduling to be too restrictive. Sunset/sunrise time changes by a few minutes each day and thus for most of the time is nowhere near a full hour. For me, a 30 min increment would be enough, but others might want it shorter. I guess we could do a poll on this.

**Comment by maciejmotyka** [comment]
Thanks for such rapid implementation!
I tested the changes and found that even though the slider allows for a 30-minute increment, the actual hour is being rounded down to a full hour, e.g. when I change 14:00 -> 15:30 it gets set to 15:00, and when I change from 16:00 -> 15:30 it gets set to 15:00.

I'm a total JS newbie, so there's a chance that I messed something up during the compilation or installation. Here's what I did:
```
git clone https://github.com/Midnight-Lizard/Midnight-Lizard.git
cd Midnight-Lizard
sudo apt install nodejs npm
sudo npm install -g typescript
sudo npm install -g webpack
sudo npm install -g webpack-cli
npm run prod-build
```
then in my browser (Vivaldi):
`vivaldi://extensions/` -> `Load unpacked` -> Selected the whole Midnight-Lizard directory -> `Open`
Also tested in Chrome.

**Comment by pavel-agarkov** [comment]
You are right.

**Comment by maciejmotyka** [comment]
Working now. Thanks!

**Comment by pavel-agarkov** [comment]
Thank you! I made it with 30 minutes interval since otherwise it would not fit into the range element without further modifications.
