### ISSUE TITLE
New version not working normally on bom.gov.au

### ISSUE THREAD

**Issue by xcasxcursex** [Midnight-Lizard/Midnight-Lizard#269]
I went to check the weather forecast today and was greeted by a lot of white areas. I checked my addons and sure enough, I had a new version.

Here's how it looks: 
![image](https://user-images.githubusercontent.com/58130821/81638679-3dec7f00-945d-11ea-9d97-b09182a3d4bc.png)

Any advice?

Edit: Seems this is happening elsewhere, too. As far as I can tell, this is making areas which are already dark, become light. For example the background on this page is set dark by userscript (which is necessary to run on all sites to avoid 'white flash') and the result is a bright background:

![image](https://user-images.githubusercontent.com/58130821/81640476-f6b4bd00-9461-11ea-8af9-095c150ae18b.png)

Disabling the userscript makes the background dark again, but the userscript does need to be there. Anyway, it's still causing issues on pages where there are dark areas. Fore xample, disabling the userscript makes one of the bright areas from the image above, become dark, but not the others (it works on the bright box onthe bottom right, but not on the ones along the left)

![image](https://user-images.githubusercontent.com/58130821/81640660-7773b900-9462-11ea-9dd7-fe8abce50655.png)

Perhaps this is related to a change I've seen in the release notes, about 'Double inversion for dark page parts'?

**Comment by pavel-agarkov** [comment]
Please provide a link to this website so I can check this out.

**Comment by xcasxcursex** [comment]
Oops sorry, it was in the title and when I found other sites, I edited it out. http://www.bom.gov.au/qld/forecasts/brisbane.shtml?ref=hdr

> Also if you are using some other extensions or user scripts that might conflict with Midnight Lizard then you have to choose witch one to use on a particular website.

It's worked fine up until this update. I can't choose - this script isto stop the infamous 'white flash' glitch.... They have to stay :( Since it worked previously I figured this was a bug in the new release and it could be fixed?

Script is just this:

`
window, html, html[loading], body, body[loading], *[loading] {
  background-color: #0f0f0f !important;
} 
`

**Comment by pavel-agarkov** [comment]
Looks like this website uses big white background image for all those areas:
http://www.bom.gov.au/images/ui/weather/day_background.png 
which is really bad idea in 2020...
To fix this problem you can decrease background (fond) images' brightness:
![image](https://user-images.githubusercontent.com/24639631/81724953-da2e7a00-948d-11ea-9143-c46c3f56b2b4.png)

**Comment by xcasxcursex** [comment]
Previous version of Midnight Lizard, 10.4.3.1, works fine. I know it's an old website but the issue I'm reporting is a change in the way Midnight Lizard works.

Here is the same page with 10.4.3.1:

![image](https://user-images.githubusercontent.com/58130821/81741997-bea18e80-94e2-11ea-965d-ab6ee3757084.png)

**Comment by pavel-agarkov** [comment]
That's correct. You can compare how background images look on the ML settings window:
#### 10.4.3:
![image](https://user-images.githubusercontent.com/24639631/81743979-3c49a800-94ab-11ea-933c-41e47e881a91.png)
#### 10.5.0
![image](https://user-images.githubusercontent.com/24639631/81744142-7d41bc80-94ab-11ea-9ef9-7046f43e5d0d.png)

So this update fixes background images when they are used correctly. I'm focusing on those correct cases since they are prevalent nowadays.

**Comment by xcasxcursex** [comment]
So do you mean, that you changed ML in a way that breaks some websites. intentionally, so you could make it work on some others?

I can't use the brightness as per the advice you gave above, as it also has this effect on the weather radar screen. I know it's an old website, but this is the only official source of weather for an entire country..... Sometimes, old websites are still important ;) Perhaps there is a better way to approach this?

**Comment by pavel-agarkov** [comment]
> So do you mean, that you changed ML in a way that breaks some websites. intentionally, so you could make it work on some others?
Yes, the whole idea of this extension is based on trade-offs in order to have a better websites coverage. When Google considered creating their own dark mode they planned to use machine learning for image recognition to decide whether each particular image should be inverted or not. Looks like they finally gave up.  
Anyway I have some ideas how to improve current situation. If you have any more examples please let me know so I can test my assumptions.

**Comment by xcasxcursex** [comment]
Sure will, thanks for taking the time to explain it :)
