### ISSUE TITLE
Settings dialog sizing

### ISSUE THREAD

**Issue by xcasxcursex** [Midnight-Lizard/Midnight-Lizard#270]
I've long had this issue and thought it was past time I reported it. I'm unsure if this is normal, but the settings dialog for the addon seems to be strangely sized. Text is very small and hard to read, and the settings do not fill the entire dialog. Here is a screenshot:

![image](https://user-images.githubusercontent.com/58130821/81638867-a63b6080-945d-11ea-9081-7ff5d402907d.png)

This is on firefox, currently nightly 78 but it's been around for some time.

**Comment by pavel-agarkov** [comment]
Yes, since Firefox does not support wider dialog windows when hidden in menu and Midnight Lizard dialog is not responsive, I had no choice to scale it down. The only option to see it with a normal scale is to not hide Midnight Lizard icon in the menu.

**Comment by xcasxcursex** [comment]
Ahh I see what you mean. All my other addons either conform to the fixed width, or open in a separate tab or window.

I tried to unpin the Midnight Lizard icon from the overflow menu, and this was the result:

![image](https://user-images.githubusercontent.com/58130821/81648618-587d2300-9472-11ea-930b-98ca61617bff.png)

**Comment by pavel-agarkov** [comment]
I cannot reproduce this. Will try more later on.

**Comment by xcasxcursex** [comment]
Just a thought: I looked at how my other addons were dealing with this and it was mostly dynamic layouts, but in your case I don't think you'd need to do anything that difficult.

The right side of the settings dialog is static, and I don't think you'd lose anything by moving it to the top or bottom. This would allow you to make it bigger so the text is readable. Since it's a dropdown, and four wide buttons, you could easily get it into one row (or two at most), rather than taking up such a large column.

**Comment by pavel-agarkov** [comment]
Unfortunately it is not that simple in my case. There are also limits on popup height so I cannot increase it any more. The only way is to make it dynamic and show/hide different parts or completely remove all advanced options into a separate page. I have no plans on doing neither of it in the nearest future.

**Comment by xcasxcursex** [comment]
Perhaps they have removed the limitations on height, I have these, among others:

<details>
<summary> Large images </summary>
![image](https://user-images.githubusercontent.com/58130821/81743611-4f796980-94e5-11ea-8946-08ea45dbe88c.png)

![image](https://user-images.githubusercontent.com/58130821/81741823-797d5c80-94e2-11ea-873f-fa68e6b708cd.png)

![image](https://user-images.githubusercontent.com/58130821/81743762-8bacca00-94e5-11ea-9747-7b2b4134a0ad.png)
</details>

**Comment by pavel-agarkov** [comment]
It only works when is hidden in menu. Otherwise it is limited to 800x600 px after witch scrollbars will be shown. But this behavior conflicts with UX recommendations for popups:
![image](https://user-images.githubusercontent.com/24639631/81745689-e9252480-94ad-11ea-81d2-fb9464ec00a9.png)
PS: Midnight Lizard popup height is exactly 600 px

**Comment by xcasxcursex** [comment]
Wow, that's very limiting, it's a shame FF works like that.

I hope you will consider a redesign in the near future so that the UI is readable.

**Comment by pavel-agarkov** [comment]
I believe it is not related to FF, other browsers have the same restriction and it most likely OS wide and caused by minimum supported screen resolution (800x600).
