### ISSUE TITLE
Settings application failed... Browser limits total sync storage... exceeded this limit

### ISSUE THREAD

**Issue by GitMurf** [Midnight-Lizard/Midnight-Lizard#271]
See screenshot for full error message. I tried following prompt by going to "global settings" tab and "switching to local storage" but there is no option for that?

Basically have to disable the extension now because unusable. Any time I try to deactivate the extension for just a specific page (like this screenshot was for xfinity stream) it gives this error and won't let me disable the theme so I am stuck with the Midnight Lizard dark css changes and only way around this is to completely turn off the extension all together which is unfortunate. 

![image](https://user-images.githubusercontent.com/64155612/82156792-3d276480-9832-11ea-9f56-59fb48bda497.png)

**Comment by pavel-agarkov** [comment]
You need to switch to local settings storage by unchecking _Sync settings across your devices_
![image](https://user-images.githubusercontent.com/24639631/82159922-75628d80-989a-11ea-8b4c-053d8a743ed6.png)
