### ISSUE TITLE
How does this compare with Dark Reader?

### ISSUE THREAD

**Issue by popey456963** [Midnight-Lizard/Midnight-Lizard#273]
The two most popular options for an extension to make webpages dark are currently [Dark Reader](https://github.com/darkreader/darkreader) and [Midnight Lizard](https://midnight-lizard.org/home).  What are the major differences and which is the best to use?

[Sibling over at Dark Reader](https://github.com/darkreader/darkreader/issues/2577)

**Comment by xcasxcursex** [comment]
The simplest answer to this question is to direct you to the settings for each addon.

**Comment by JustYourAverageGithubUser** [comment]
Midnight Lizard is far more customizable.

**Comment by xcasxcursex** [comment]
> Midnight Lizard is far more customizable.

Which is why I directed OP to the settings for each addon.

However, Dark Reader has had some upgrades lately and the difference is not so significant as it used to be.
