### ISSUE TITLE
Theme isn't getting applied to firefox's new tab and preferences pages

### ISSUE THREAD

**Issue by hiteshsharma** [Midnight-Lizard/Midnight-Lizard#275]

**Comment by pavel-agarkov** [comment]
New Tab processing by extensions is now forbidden by all browsers.
You need to use special kind of extensions that replace default New Tab with their own web page with encapsulated dark theme. (I use [this one](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/))

As for dark theme in Firefox settings - it is also forbidden for extensions to access.
Here's a tutorial how to enable dark theme in Firefox settings UI: https://news.softpedia.com/news/how-to-enable-the-dark-mode-in-mozilla-firefox-settings-ui-525673.shtml
PS: I personally don't use this method and don't know why it is dark for me...
