### ISSUE TITLE
Enable support for toggling on/off for in-directories

### ISSUE THREAD

**Issue by JoshuaQuinlan** [Midnight-Lizard/Midnight-Lizard#278]
Hi,

I would like to be able to toggle the plugin on/off for in-directories, not just by domain.

Here's an example. I work at a hosting company, and our customer control panel has a dark theme (so I don't want the plugin running on that), but our admin panel (domain.com/admin) does not (so I would like it running there).

Would you please be able to add this functionality? It would be HUGELY helpful!

Many thanks.

**Comment by pavel-agarkov** [comment]
You can use "Exclude match patterns" to specify concrete url where you don't want to use Midnight Lizard
![image](https://user-images.githubusercontent.com/24639631/83656114-d511a600-a5c7-11ea-8710-3c856e427517.png)

**Comment by JoshuaQuinlan** [comment]
Amazing. I don't know how I missed this. It's working brilliantly for me.
Loving the plugin! Thanks so much.

**Comment by JoshuaQuinlan** [comment]
Would it be possible to override an exclude match pattern. For example:

Include: https://domain.com/admin/support/*
Exclude: https://domain.com/*

**Comment by pavel-agarkov** [comment]
Exclude rules are applied after all other rules so they cannot be overridden.
But you can achieve this behavior by unchecking "Run on this website" and providing include rule as you stated. You can find this description in field hints on the settings form as well.
