### ISSUE TITLE
Setting "processing mode" to "filter" on Firefox white-screens

### ISSUE THREAD

**Issue by chrisgraham** [Midnight-Lizard/Midnight-Lizard#283]
If I change the processing mode to filter in the settings, the whole extension pane turns white, and I have to close it and reopen it to continue configuration.

Firefox 77.0.1, Linux, Gnome.

**Comment by pavel-agarkov** [comment]
I cannot reproduce this. Can you please provide a screenshot?

**Comment by chrisgraham** [comment]
I made a screencast that should be easier to reproduce from:
https://www.dropbox.com/s/a8zqnpudhdlhxgg/midnight-lizard-white-screen.mp4?dl=0

Note I found that Midnight Lizard has to be on, with a scheme set, for it to happen. You can either have it on and select Filter to reproduce, or select Filter then turn on to reproduce (my screencast shows the latter).

**Comment by pavel-agarkov** [comment]
Looks like when there is absolutely no filter Firefox for some reason displays just white background.
Other browsers do nothing in this case but anyway there is no value in Increased Contrast color scheme with Filter mode.
