### ISSUE TITLE
Using the extension for local PDFs

### ISSUE THREAD

**Issue by Tschipp** [Midnight-Lizard/Midnight-Lizard#295]
In the README.md it says:

> Use with PDF and local files (enable in browser settings)

How exactly is this done? What browser settings need to be enabled and where are they?

**Comment by pavel-agarkov** [comment]
In chromium based  browser  go to 
chrome://extensions/?id=pbnndmlekkboofhnbonilimejonapojg
![image](https://user-images.githubusercontent.com/24639631/89712109-653ce480-d997-11ea-8d10-7e15e9d7214f.png)

**Comment by Tschipp** [comment]
Thanks, you just saved my eyes :) Maybe worth including in the README?
