### ISSUE TITLE
Feature request: Blacklisting

### ISSUE THREAD

**Issue by krizalidzero** [Midnight-Lizard/Midnight-Lizard#299]
Currently we have a whitelist, but I want to use this plugin the other way around; I would like an inverse activation mode.
In other words, I would like to have the plugin active at all times, but be able to blacklist sites.
The sites on the black list would go dark mode as specified by the extension.

Example: Enable extension > all sites unmodified > blacklist pesky ultra bright white site > pesky ultra bright white site becomes legible thanks to the extension but all other sites remain normal unless blacklisted too.

Which is the opposite of how all of these extensions work.
I would like the option to invert and toggle between these two modes (whitelisting and blacklisting).

Thanks.

**Comment by pavel-agarkov** [comment]
There is already a toggle that works exactly as you described:
![image](https://user-images.githubusercontent.com/24639631/91287028-e0740800-e797-11ea-91e9-a2f1c8dbeb9e.png)
Just uncheck it.
