### ISSUE TITLE
Extension popup behaves weirdly with page zoom setting

### ISSUE THREAD

**Issue by Elduris** [Midnight-Lizard/Midnight-Lizard#301]
After setting the page zoom in Chrome settings to 125%, I noticed scrollbars appeared in the Midnight Lizard's settings popup as its contents don't fit it anymore. I fiddled with the site zoom in the changelog page in an attempt to fix it, but setting it to lower than 125% doesn't seem to do anything, while setting it higher produces a weird behavior. Every time I open the popup after setting a higher zoom, it will, seemingly randomly, either show the scrollbars as before or show the content tinier than normal with the popup fitting it horizontally, but filled with black up to the normal height. The higher the zoom the tinier it'll be with the exception of 150%, which will alternate the normal popup with the one with scrollbars.
![image](https://user-images.githubusercontent.com/32915094/92302385-1fe1e780-ef42-11ea-93a8-dc4a9de224c0.png)
![image](https://user-images.githubusercontent.com/32915094/92302390-31c38a80-ef42-11ea-8279-3e8e5e96fb6c.png)

**Comment by midnight-lizard-extension** [comment]
You have to set page zoom on changelog page to 100% in order for popup to work properly - Chrome uses the same scale for all pages of a website and popup is considered as a page of an extension website.

**Comment by Elduris** [comment]
Sorry, I guess I didn't make it clear enough, but when I said anything lower than 125% does nothing that includes 100%
![image](https://user-images.githubusercontent.com/32915094/92824809-3a361e00-f3a5-11ea-873c-627ddbaae68c.png)

**Comment by midnight-lizard-extension** [comment]
Yes, I misunderstood the problem. Midnight Lizard does not support global browser scaling.
But it works with global OS scaling very well.
Global OS scaling also scales all panels so it is much more consistent.
