### ISSUE TITLE
Feature: Disable schedule (always on) switch

### ISSUE THREAD

**Issue by beepee123** [Midnight-Lizard/Midnight-Lizard#306]
Greetings,

I prefer to manually enable/disable on individual websites as I typically work in a darkened room without windows at all times.

Does setting the Activation and Deactivation time to the same value effectively disable the schedule feature? It would be helpful if this was indicated. Even better would be a simple switch to disable the schedule entirely - for individual sites or globally.

Also wanted to say that this extensions has the best "auto" night mode algorithm I have seen! Other extensions I have tried use really lazy (and ugly) hacks. Thank you for the hard work!

**Comment by pavel-agarkov** [comment]
Schedule is disabled by default - so the extension is always enabled by default.
Setting Activation time to 0 and Deactivation time to 24 de facto disables schedule since the extension will be enabled all the time.
