### ISSUE TITLE
Chrome extension seems like it's zoomed in (it's not, though)

### ISSUE THREAD

**Issue by NorthLake** [Midnight-Lizard/Midnight-Lizard#307]
I've had this issue for a while now thinking that it would be noticed pretty easily, but apparently not everyone experiences it.
Every time I open the popup it seems like it zooms in a little while loading. I've opened the URL of the popup in a new tab, and I can confirm that it's not zoomed in.
I've dug a little deeper, and it appears to be caused by the style property `--popup-scale` being applied to the html element. It's set to set to `1.17647`, and can't be changed. What I mean by that is that it's immediately reverted back to that value when I manually change it. Why is that property applied? It seems to serve no actual purpose for me, because I feel like `1` would be just fine.

![image](https://user-images.githubusercontent.com/20684682/100634734-f4e41580-332f-11eb-9256-25f80ddf0035.png)

**Comment by pavel-agarkov** [comment]
Looks like Dutch translation is too long and causing this effect.
I will fix it in the next release.
PS: You can help me to shorten this [text](https://translate.midnight-lizard.org/translate/midnight-lizard/4/en-nl#193)
