### ISSUE TITLE
[Documentation] Use with PDF and local files

### ISSUE THREAD

**Issue by ClemaX** [Midnight-Lizard/Midnight-Lizard#310]
The procedure to enable PDF and local files styling is unclear.

```Use with PDF and local files (enable in browser settings)```
1. Do all browsers support this feature?
2. Where do we find the corresponding setting?

PS: I'm currently using Firefox

Edit:
This is a duplicate of #295, but the issue is not solved IMO.

**Comment by pavel-agarkov** [comment]
Looks like in Firefox local files processing is enabled by default.
But as for PDF - long time ago they switched to a new plugin for PDF and now other extensions cannot access it.
So it is impossible to style PDF files without creating custom PDF viewer which is not in the scope of this project.
