### ISSUE TITLE
disable debug log

### ISSUE THREAD

**Issue by maico910** [Midnight-Lizard/Midnight-Lizard#311]
Has some way to disable these logs in console? I am developer and it's disturbing my work

![image](https://user-images.githubusercontent.com/24510745/102790509-4b1f0400-4384-11eb-9c10-0cb1363420ee.png)

Or have some way to disable `this._app.isDebug`?

![image](https://user-images.githubusercontent.com/24510745/102791941-815d8300-4386-11eb-95f9-f4bd6e72b32b.png)

**Comment by pavel-agarkov** [comment]
When extension is from official source then isDebug suppose to be false.
What browser do you use and how has Midnight Lizard been installed?

**Comment by maico910** [comment]
Sorry, I forgot these information

I'm using 
Microsoft Edge 64bits version 87.0.664.66
Midnight Lizard v10.6.0

**Comment by pavel-agarkov** [comment]
In the next release I'm going to fix this by switching to https://developer.chrome.com/docs/extensions/reference/management/#type-ExtensionInstallType
instead of hardcoded extension ids
