### ISSUE TITLE
Keyboard Shortcut Config [Feature Request]

### ISSUE THREAD

**Issue by andynameistaken** [Midnight-Lizard/Midnight-Lizard#320]
# Issue:
Key combination `Alt + Shift + L` is used for diacritical characters in some keyboard layouts (ex. Polish). 
It would be nice to be able to change it to avoid collisions.

Whatever the future brings, thank you for your work.

**Comment by pavel-agarkov** [comment]
In **Chromium** based browsers: https://www.webnots.com/how-to-assign-keyboard-shortcuts-to-chrome-extensions/
![image](https://user-images.githubusercontent.com/24639631/107112334-e2261980-6867-11eb-90ad-0885d0b3ef4c.png)


In **Firefox**: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
![image](https://user-images.githubusercontent.com/24639631/107112262-50b6a780-6867-11eb-8b24-0837d2bcb6e5.png)
