### ISSUE TITLE
Performance issue on Google Spreadsheet

### ISSUE THREAD

**Issue by Geobert** [Midnight-Lizard/Midnight-Lizard#322]
Hi!

I'm comparing Dark reader and Midnight Lizard with a strong preference on ML for its color scheme but I can't use it on Google Spreadsheet: the page takes forever to render on any event (scrolling, edit…).

Even on Filter mode.

ML version: 10.7.1
Firefox nightly 88.0a1 (2021-03-05)

**Comment by pavel-agarkov** [comment]
What processing mode do you use now?
Have you tried another one?
![image](https://user-images.githubusercontent.com/24639631/110149432-18b36d80-7def-11eb-928c-69203f607f3a.png)

I do use it on Google Spreadsheets all the time without problems but probably I just got used to it:)

**Comment by Geobert** [comment]
On filter, I get a grey screen with Filter mode and Discord Dark scheme. but it seems that Dimmed Dust and Filter mode works
