### ISSUE TITLE
Save moves Current to Default

### ISSUE THREAD

**Issue by Gubith** [Midnight-Lizard/Midnight-Lizard#325]
Issue: **Save** Current color scheme changes the Current selection to Default.  

I like to make one adjustment,  apply,  save, then make another.   But,  it auto switches to default scheme, so my next change is applied to 'custom' instead - and I have to find the tab again to continue working.  IMO the scheme and tab I'm working on should remain in focus.

1) Select Halloween
2) Select Buttons
3) Change "Default hue' to a cyan color
4) Apply
5) Observe 'Current color scheme' remains on Halloween (good)
6) Save
7) Observe 'Current color scheme' switched to Default,  (and 'Buttons' is no longer in focus!)
8) Click Buttons (assuming we're still on Halloween, we're not!)
9) Set Hue to Orange
10) Observe 'Current color scheme' switched to Custom (?!)
10) Apply
11) Observe Save button missing (no need to save custom, but this seems weird)
12) Select Halloween 
13) Observe that Button hue is not Orange.
14) Set Hue to Orange (again...)
15) Apply/Save
16) Observe Scheme Default again...

Did I make that Orange 15 or Orange 21?  I'll have to click a few times to get back to that page!

**Comment by pavel-agarkov** [comment]
You should not press Apply before color scheme is saved otherwise it will create custom unnamed color scheme and loose reference to the original color scheme you were editing. It is dome because people asked to be able to apply custom color scheme on a particular website without necessity to add this color scheme to the global list.

**Comment by Gubith** [comment]
If I save it and decide to go back?   I use ctrl-z all the time, not sure if it's possible here...

**Comment by pavel-agarkov** [comment]
Midnight Lizard does not keep track of all changes so there is no way to undo changes. But you can export color schemes in order to back them up.
