### ISSUE TITLE
Support Edge

### ISSUE THREAD

**Issue by pavel-agarkov** [Midnight-Lizard/Midnight-Lizard#33]
add likes to this comment to support Edge

**Comment by stonecrusher** [comment]
So [this works](https://microsoftedge.microsoft.com/addons/detail/cphiklljfgkgjhbmmjifjknodgbkllaj), doesn't it? And it's official? Because I can't see it on https://midnight-lizard.org/home

**Comment by pavel-agarkov** [comment]
Yes, it is official and works if you are using latest Chromium based version of Edge.
Original Chrome Web Store version also works there.
With next release website will be updated as well.
