### ISSUE TITLE
Question: how to make color scheme only take effect on certain websites?

### ISSUE THREAD

**Issue by Gd-Gordon** [Midnight-Lizard/Midnight-Lizard#330]
Now by default a color scheme is applied to all website except those being manually added to blocklist. Is it possible to make it work in a reversed way? For example, it only applies color scheme to certain allowed websites and makes no change to any other websites at the first time visiting them.

**Comment by pavel-agarkov** [comment]
Yes, this is possible.
You can switch from blocklist to allowlist mode by unchecking `Run on all websites by default` on the `Global settings` tab.

**Comment by Gd-Gordon** [comment]
Cool. It just does what I want. Thank you so much!
