### ISSUE TITLE
github ipynb file show white 

### ISSUE THREAD

**Issue by actforjason** [Midnight-Lizard/Midnight-Lizard#335]
![image](https://user-images.githubusercontent.com/57058325/128329212-6f8aafaa-109f-4498-bca3-63dd9dbba04b.png)

**Comment by pavel-agarkov** [comment]
Looks like this file format has some custom processing and conflicts with Midnight Lizard.
I would recommend disabling Midnight Lizard on GitHub with Alt+Shift+L and using built-in GitHub dark theme.

**Comment by actforjason** [comment]
Yes，that's a good alternative.
