### ISSUE TITLE
Feature Request: faster way to switch to Original (none)

### ISSUE THREAD

**Issue by jnorris441** [Midnight-Lizard/Midnight-Lizard#341]
There are many cases where Midnight Lizard is less optimal than the existing styles, but to disable it you have to 

1. open the extension
2. click the theme dropdown
3. choose original
4. click apply

It would be nice if you could do it with fewer clicks or a keyboard shortcut

**Comment by pavel-agarkov** [comment]
There are already keyboard shortcuts exactly for that:
Current website: Alt+Shift+L
Global: Alt+Shift+M

Also you can do the same just by clicking on the current website title in the Midnight Lizard settings popup
