### ISSUE TITLE
Advanced Rules to disable/re-enable on certain websites URLs

### ISSUE THREAD

**Issue by adRn-s** [Midnight-Lizard/Midnight-Lizard#345]
Hi, I am in the situation where I want to disable on a URL, say <https://some.domain.com>, but I want ML to process a path, say <https://some.domain.com/admin>. Is this possible?

**Comment by pavel-agarkov** [comment]
Yes this is possible.
Disable Midnight Lizard while you are on https://some.domain.com/ with Alt+Shift+L
Then go to the Activation tab and set Include match patterns to https://some.domain.com/admin*
And press Apply
