### ISSUE TITLE
Youtube low brightness

### ISSUE THREAD

**Issue by ghost** [Midnight-Lizard/Midnight-Lizard#351]
Brigthness is toned down for youtube page (rest of the web isn't). Main player is the only exception. This is the same behaviour, irrespective of the color scheme (even with custom generator). Is this behaviour intentional?
https://ibb.co/NNhNSFd
And there's a weird black box like behaviour in the main player, which looks unusual.
https://ibb.co/MCBmYLW

**Comment by pavel-agarkov** [comment]
you can also ask questions in telegram for example
1) you can change default image brightness on the corresponding tab. yes, by default it is slightly dimmed.
2) you can set processing mode to the complex to avoid this behavior. currently it is a simplified mode on your screen.
<img width="510" alt="processing-mode" src="https://user-images.githubusercontent.com/24639631/173056915-cd61b0e4-c52a-49d3-8194-157445c0720c.png">

**Comment by ghost** [comment]
Tq. Fixed. But is the complex processing mode supposed to be performance intensive?
Also if Automatic mode is designed to change simplified to complex based on the number of elements, that means youtube main page has less elements than what you've had for complex.
Atleast a site blacklist for processing mode should exist if this is the behaviour.

And no. Telegram is not a viable medium. This issue section is all we need, since many users mostly search issues & doubts here.
