### ISSUE TITLE
Midnight-Lizard impact performance too much

### ISSUE THREAD

**Issue by 3oheicrw** [Midnight-Lizard/Midnight-Lizard#353]
Compared to Dark Reader and Dark Background And Light Text, Midnigh-Lizard impacted the performance of websites too much, the loading speed of websites are severely affected when the extension is on so even though I liked the color scheme of it very much I have to disable it and use other similar extensions most of the time. I wonder why it impacted the performance that much and why this has not yet been fixed?

**Comment by pavel-agarkov** [comment]
All three extensions you've mentioned are using different techniques to achieve their results each one with its own benefits and compromises. Midnight Lizard compromises performance in favor of a subjective visual excellence.

**Comment by 3oheicrw** [comment]
> All three extensions you've mentioned are using different techniques to achieve their results each one with its own benefits and compromises. Midnight Lizard compromises performance in favor of a subjective visual excellence.

Midnight-Lizard is nothing excellent compared to the others. What I loved about it is the color scheme. The most excellent in both of performance and compatibility is Dark Reader. But I don't like the color scheme and too lazy to customize it to mimic Midnight-Lizard color scheme. Dark Background And Light Text served with another purpose, when my eyes are truly tired and Dark Reader (and Midnight-Lizard too) 's not really dark color scheme is not enough. Dark Background And Light Text is nothing but a black background and white text like a chalk board. When even Dark Background And Light Text no longer work I will consult the Operating system's High contrast theme :smile:

**Comment by 3oheicrw** [comment]
The technology behind Midnight-Lizard is nothing excellent at all. I'm sorry. It's not deliver better compatibility to websites nor it's better in performance. It breaks sites very regular. Take this forum as an example and so do all other Xenforo forum:

https://forums.freebsd.org/

When you writing reply the toolbar is all white. You have to click to expand that bar to have it properly styled by Midnight-Lizard. Midnight-Lizard is the only addons suffered to this. Both Dark Reader and Dark Background And Light Text have no such problem. This is enough to show to excellent of Midnight-Lizard's visual quality?
