### ISSUE TITLE
Midnight-Lizard broken twitter

### ISSUE THREAD

**Issue by 3oheicrw** [Midnight-Lizard/Midnight-Lizard#354]
"Don't miss what is happening" is always at the top of the site and when you scroll down it is go down with you and hide the posts that you wanted to see. When Midnight-Lizard was turned off "Don't miss what is happening" is correctly put at the bottom of the site and don't interfere with the content. I tried both Dark Reader and Dark Background And Light Text, none of them caused such problem.

**Comment by pavel-agarkov** [comment]
You can disable Midnight Lizard on Twitter with Alt+Shift+L keyboard shortcut and use their builin dark theme.

**Comment by 3oheicrw** [comment]
> You can disable Midnight Lizard on Twitter with Alt+Shift+L keyboard shortcut and use their builin dark theme.

This answer is totally unexpected. Midnight-Lizard is uninstalled and good bye you.
