### ISSUE TITLE
Additional Color Schemes Not Working in Firefox

### ISSUE THREAD

**Issue by andynameistaken** [Midnight-Lizard/Midnight-Lizard#357]
When visiting page with Firefox (102.0.1) pages does not recognize the fact the plugin is installed:
![image](https://user-images.githubusercontent.com/15692002/178762988-19a10ec1-ca52-4280-800d-ee0292bbf7e7.png)

**Comment by pavel-agarkov** [comment]
the plugin has to be enabled in order to be recognized by the website

**Comment by icemanmelb** [comment]
Im also having the same issue with the same browser version and Im on a Mac. Not sure if that's the issue. Ive turned off my Adguard adblocker, Ghostery and NoScript Extension as well. The Plugin is running as I can changed the build-in Color Schemes.

Update:  It works! Restarted turned off a few more extension. Reboot the browser and it's back. Not sure what was the cause but now works.

**Comment by EricWong1994** [comment]
I have the same issue in Edge Browser today. I turn off all extension , restart computer twice. turn off my settings in browser like avoid tracking and so on.  but it still not work.
Then I uninstall the midnight plugin and reinstall. It works. 
It's so weird.
![image](https://user-images.githubusercontent.com/48429995/217759301-c9e44f3f-be4c-4a7f-a93b-dea7c0e33364.png)
