### ISSUE TITLE
QuotaExceedError: storage.sync API call

### ISSUE THREAD

**Issue by ejazrasool** [Midnight-Lizard/Midnight-Lizard#359]
This extension has been working fine but for a couple of days I have started a "QuotaExceedError: storage.sync API call exceeded its quota limitations" error while enabling the extension for a new website. Refreshing the page shows the website in its original colorscheme
![2022-08-23](https://user-images.githubusercontent.com/4628021/186123354-ff50e272-0584-4f29-83d3-d5b0ed5ab9e1.jpg)
.

**Comment by pavel-agarkov** [comment]
It is very hard to fix this and keep using the settings synchronization so the easiest way to stop synchronization.
You can do it on the global settings tab
<img width="492" alt="sync-storage" src="https://user-images.githubusercontent.com/24639631/186140065-755bf0e0-24f0-48f0-8af4-2a25e77979b2.png">
