### ISSUE TITLE
I see no way to turn it on and off, short of disabling the extension

### ISSUE THREAD

**Issue by Andy2No** [Midnight-Lizard/Midnight-Lizard#361]
Other night mode type add-ons come with an off switch.  I don't see one for this, though that could possibly be due to the fact that the user interface is far too small for me to read #360

It seems all I can do is disable the add-on in Firefox's "Add-ons and themes" tab.

**Comment by pavel-agarkov** [comment]
If the UI is too small for you then you can use keyboard shortcuts
Alt+Shift+L - toggle current website
Alt+Shift+M - toggle extension
