### ISSUE TITLE
User interface switches to a bright background, when disabled for a particular website

### ISSUE THREAD

**Issue by Andy2No** [Midnight-Lizard/Midnight-Lizard#362]
If I disable the add-on for a particular website, the user interface becomes very bright, because it switches itself to a bright background.

The reason I want to use an add-on like this is because I find most website too bright, which hurts my eyes, and causes eye strain and headaches.  Ideally, I'd prefer it if the add-on I use to do that doesn't add to the problem itself.

I gather it themes itself based on the theme being applied to a website, but only when it's enabled for that website.  I think it's a fair assumption that most people who want an add-on like this want it to stay dark, all of the time.

Perhaps it could have a theme applied when its turned off that has a dark background, instead of what it does now?

As an example, here it is used with google.co.uk, which is set to the Dark theme.  When I disable the add-on for that site, the user interface for it becomes uncomfortably bright:

On for site:

![UI dark when enabled for site gif](https://user-images.githubusercontent.com/8021302/189298807-766dfc00-01a0-4b43-a04b-acf60a67b221.gif)

Off for site:

![UI bright when not enabled for site](https://user-images.githubusercontent.com/8021302/189298830-a8ccea7c-8e04-4a72-a4ac-95e21e44c17a.gif)

**Comment by pavel-agarkov** [comment]
yes, it is by design.
this extension is not just dark mode - it has bright color schemes as well and users can create their own as well.
So there is no assumption that it should be dark by default. Also a lot of people use it only half of the day so they want the UI to be bright during the day when extension is disabled.

**Comment by Andy2No** [comment]
If someone is using this at night, they will have the add-on enabled, but will often have to disable it for certain sites - ones where it doesn't work well, especially if those sites have their own dark mode. 

In those circumstances, they will find it unpleasant when this happens - they're working in dim lighting, and they have this in use because they want the screen to stay dark.  Suddenly flooding the screen with light, as they change a setting, is not likely to be a popular choice.
