### ISSUE TITLE
Generating a CSS file from the `Midnight Lizard` config?

### ISSUE THREAD

**Issue by GamePlayer-8** [Midnight-Lizard/Midnight-Lizard#373]
Heyo,

As the title says, is it possible to generate a single (or multiple) CSS files from the config?

**Comment by pavel-agarkov** [comment]
at least it is possible to copy main colors from the css variables that are injected to each processed web page
![image](https://github.com/Midnight-Lizard/Midnight-Lizard/assets/24639631/6ae99e3d-9a57-4b52-b87e-06bcc0cbecf1)
