### ISSUE TITLE
Sometimes eats a lot of RAM, makes sites laggy. No more updates?

### ISSUE THREAD

**Issue by katastrophe92** [Midnight-Lizard/Midnight-Lizard#374]
Hi MidnightLizard community,

First of all thank you for this amazing repository, I really LOVE IT

Does anyone know why sometimes consume so much RAM and makes sites unresponsive? I do not know how to reproduce it , it just happens. If I have a lot of tabs opened or not. It happens on LibreWolf browser. Now I will test it on Brave browser. 
This repository/extension is still maintained by someone or a branch of it? I love it and is more capable than other dark mode extensions and is sad to see that it has no more updates in a long time. Somebody know a similar open source extension?

**Comment by dziban303** [comment]
Seems this extension has been abandoned. Real bummer
