### ISSUE TITLE
Additional `Disable for that site` & `Disable for all sites` buttons in the OptionMenu.

### ISSUE THREAD

**Issue by GamePlayer-8** [Midnight-Lizard/Midnight-Lizard#375]
Heyo,

Typically some sites might be laggy due to CSS replacing. What about adding `Disable for that site` & `Disable for all sites` buttons in the OptionMenu what appear when right-clicking on the extension / page elements?

**Comment by pavel-agarkov** [comment]
Midnight Lizard already has similar functionality in the popup menu and also with keyboard shortcuts
