### ISSUE TITLE
How to change the shortcut used to activate\disable on current site?

### ISSUE THREAD

**Issue by slrgt** [Midnight-Lizard/Midnight-Lizard#393]
I want to change the shortcut so its alt shift A to disable or enable the extension on the current site

**Comment by pavel-agarkov** [comment]
If used on Chrome
- Go to chrome://extensions/shortcuts
- Find Midnight Lizard
- Set shortcut you want
![image](https://github.com/Midnight-Lizard/Midnight-Lizard/assets/24639631/44fe7004-5e6f-442f-85b7-dd7de406b618)

**Comment by slrgt** [comment]
Is this possible on firefox?

**Comment by pavel-agarkov** [comment]
Sure
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
