### ISSUE TITLE
Feature request: also switch the Firefox theme when changing to dark mode.

### ISSUE THREAD

**Issue by hboetes** [Midnight-Lizard/Midnight-Lizard#394]
Currently, I have to manually switch the Firefox theme, when switching to dark mode. Wouldn't it be nice if the theme was switched automatically as well?

**Comment by pavel-agarkov** [comment]
there is an option to change Firefox theme by Midnight Lizard
![image](https://github.com/user-attachments/assets/e579f651-7b2c-4c9f-88e4-3f580de8b062)

**Comment by hboetes** [comment]
Thanks, much appreciated!
