### ISSUE TITLE
Allow developers to disable dark mode on their site

### ISSUE THREAD

**Issue by ping-maxwell** [Midnight-Lizard/Midnight-Lizard#395]
Dark reader, another common extension allows for devs to pass a `<meta>` tag into the header to disable the extension from applying a dark theme to that site.
Maybe a similar idea can be implemented here as well?

Dark reader's approach:
```html
<meta name="darkreader-lock" />
```

**Comment by pavel-agarkov** [comment]
Midnight Lizard has a similar option
```css
body {
    --ml-ignore: true;
}
```
and this way you can also disable Midnight Lizard for a specific element(s)
